import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  DownloadOutline,
  UploadOutline,
  FileExcelOutline,
  FileTextOutline,
  InboxOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  ExclamationCircleOutline,
  InfoCircleOutline,
  ReloadOutline,
  UserOutline,
  UserSwitchOutline,
  HomeOutline,
  DeleteOutline,
  PlusOutline,
  TeamOutline,
  UsergroupAddOutline,
  UserAddOutline,
  EyeOutline,
  CloudSyncOutline,
  ArrowLeftOutline,
  BarChartOutline,
  FilterOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  DownloadOutline,
  UploadOutline,
  FileExcelOutline,
  FileTextOutline,
  InboxOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  ExclamationCircleOutline,
  InfoCircleOutline,
  ReloadOutline,
  UserOutline,
  UserSwitchOutline,
  HomeOutline,
  DeleteOutline,
  PlusOutline,
  TeamOutline,
  UsergroupAddOutline,
  UserAddOutline,
  EyeOutline,
  CloudSyncOutline,
  ArrowLeftOutline,
  BarChartOutline,
  FilterOutline,
];


